CREATE TABLE `QUESTION` (

`ID` int NOT NULL AUTO_INCREMENT COMMENT '题号',

`CONTEXT` text NOT NULL COMMENT '题干',

`A` text NULL COMMENT 'A选项',

`B` text NULL COMMENT 'B选项',

`C` text NULL COMMENT 'C选项',

`D` text NULL COMMENT 'D选项',

`RIGHT_ANSWER` char(8) NOT NULL COMMENT '正确答案',

`TYPE` int NOT NULL COMMENT '类型',

PRIMARY KEY (`ID`) 

)

COMMENT = '题库表';



CREATE TABLE `EXAM` (

`ID` int NOT NULL AUTO_INCREMENT,

`NAME` text NOT NULL COMMENT '考试名称',

`LIMITED_TIME` int NOT NULL COMMENT '限制时间',

`ACTION_DATE` date NOT NULL COMMENT '开考日期',

`ACTION_TIME` time NOT NULL COMMENT '开考时间',

`ACTION_PLACE` text NULL COMMENT '考场',

PRIMARY KEY (`ID`) 

)

COMMENT = '考试表';



CREATE TABLE `USER` (

`ID` varchar(64) NOT NULL COMMENT '学号或工号',

`PASSWORD` varchar(128) NOT NULL COMMENT 'md5存储的密码',

PRIMARY KEY (`ID`) 

);



CREATE TABLE `CHARPTER` (

`ID` int NOT NULL AUTO_INCREMENT COMMENT '章节编号',

`NAME` varchar(256) NOT NULL COMMENT '章节列表',

PRIMARY KEY (`ID`) 

)

COMMENT = '章节列表';



CREATE TABLE `ANSWER` (

`ID` int NOT NULL AUTO_INCREMENT COMMENT '作答流水号',

`ANSWER` varchar(8) NOT NULL COMMENT '填写的答案',

`USER` varchar(64) NOT NULL COMMENT '考生',

`QUESTION_ID` int NOT NULL COMMENT '试题的编号',

`SCORE` bit NOT NULL COMMENT '得分（0/1）',

`EXAM` int NOT NULL COMMENT '所属的考试',

PRIMARY KEY (`ID`) 

)

COMMENT = '学生作答表';



CREATE TABLE `TYPE` (

`ID` int NOT NULL AUTO_INCREMENT COMMENT '类型编号',

`NAME` varchar(32) NOT NULL COMMENT '类型名称',

PRIMARY KEY (`ID`) 

);



CREATE TABLE `POWER` (

`ID` int NOT NULL AUTO_INCREMENT COMMENT '权限编号',

`POWER` varchar(256) NOT NULL COMMENT '权限名称',

PRIMARY KEY (`ID`) 

)

COMMENT = '权限列表，前端渲染条件与该表对应';



CREATE TABLE `COURSE` (

`ID` int NOT NULL AUTO_INCREMENT COMMENT '课程编号',

`NAME` varchar(256) NOT NULL COMMENT '课程名称',

PRIMARY KEY (`ID`) 

)

COMMENT = '课程列表';



CREATE TABLE `TYPE_POWER` (

`TYPE` int NOT NULL,

`POWER` int NOT NULL,

PRIMARY KEY (`TYPE`, `POWER`) 

);



CREATE TABLE `USER_TYPE` (

`USER` varchar(64) NOT NULL,

`TYPE` int NOT NULL,

PRIMARY KEY (`USER`, `TYPE`) 

);



CREATE TABLE `QUESTION_EXAM` (

`EXAM` int NOT NULL,

`QUESTION` int NOT NULL

);



CREATE TABLE `CHARPTER_COURSE` (

`CHARPTER` int NOT NULL,

`COURSE` int NOT NULL,

PRIMARY KEY (`CHARPTER`, `COURSE`) 

);



CREATE TABLE `QUESTION_CHARPTER` (

`QUESTION` int NOT NULL,

`CHARPTER` int NOT NULL,

PRIMARY KEY (`QUESTION`, `CHARPTER`) 

);





ALTER TABLE `QUESTION_EXAM` ADD CONSTRAINT `fk_QUESTION_EXAM_EXAM_1` FOREIGN KEY (`EXAM`) REFERENCES `EXAM` (`ID`);

ALTER TABLE `QUESTION_EXAM` ADD CONSTRAINT `fk_QUESTION_EXAM_QUESTION_1` FOREIGN KEY (`QUESTION`) REFERENCES `QUESTION` (`ID`);

ALTER TABLE `QUESTION_CHARPTER` ADD CONSTRAINT `fk_QUESTION_CHARPTER_QUESTION_1` FOREIGN KEY (`QUESTION`) REFERENCES `QUESTION` (`ID`);

ALTER TABLE `QUESTION_CHARPTER` ADD CONSTRAINT `fk_QUESTION_CHARPTER_CHARPTER_1` FOREIGN KEY (`CHARPTER`) REFERENCES `CHARPTER` (`ID`);

ALTER TABLE `CHARPTER_COURSE` ADD CONSTRAINT `fk_CHARPTER_COURSE_CHARPTER_1` FOREIGN KEY (`CHARPTER`) REFERENCES `CHARPTER` (`ID`);

ALTER TABLE `CHARPTER_COURSE` ADD CONSTRAINT `fk_CHARPTER_COURSE_COURSE_1` FOREIGN KEY (`COURSE`) REFERENCES `COURSE` (`ID`);

ALTER TABLE `ANSWER` ADD CONSTRAINT `fk_ANSWER_USER_1` FOREIGN KEY (`USER`) REFERENCES `USER` (`ID`);

ALTER TABLE `ANSWER` ADD CONSTRAINT `fk_ANSWER_EXAM_1` FOREIGN KEY (`EXAM`) REFERENCES `EXAM` (`ID`);

ALTER TABLE `USER_TYPE` ADD CONSTRAINT `fk_USER_TYPE_USER_1` FOREIGN KEY (`USER`) REFERENCES `USER` (`ID`);

ALTER TABLE `USER_TYPE` ADD CONSTRAINT `fk_USER_TYPE_TYPE_1` FOREIGN KEY (`TYPE`) REFERENCES `TYPE` (`ID`);

ALTER TABLE `TYPE_POWER` ADD CONSTRAINT `fk_TYPE_POWER_TYPE_1` FOREIGN KEY (`TYPE`) REFERENCES `TYPE` (`ID`);

ALTER TABLE `TYPE_POWER` ADD CONSTRAINT `fk_TYPE_POWER_POWER_1` FOREIGN KEY (`TYPE`) REFERENCES `POWER` (`ID`);



