CREATE TABLE `QUESTION` (
`ID` int NOT NULL,
`CONTEXT` text NOT NULL,
`A` text NULL,
`B` text NULL,
`C` text NULL,
`D` text NULL,
`RIGHT_ANSWER` char(8) NOT NULL,
`TYPE` int NOT NULL,
PRIMARY KEY (`ID`) 
);

CREATE TABLE `EXAM` (
`ID` int NOT NULL AUTO_INCREMENT,
`NAME` text NOT NULL,
`LIMITED_TIME` int NOT NULL,
`ACTION_DATE` date NOT NULL,
`ACTION_TIME` time NOT NULL,
`ACTION_PLACE` text NULL,
PRIMARY KEY (`ID`) 
);

CREATE TABLE `USER` (
`ID` varchar(64) NOT NULL,
`PASSWORD` varchar(128) NOT NULL,
PRIMARY KEY (`ID`) 
);

CREATE TABLE `CHARPTER` (
`ID` int NOT NULL,
`NAME` varchar(256) NOT NULL,
PRIMARY KEY (`ID`) 
);

CREATE TABLE `ANSWER` (
`ID` int NOT NULL AUTO_INCREMENT,
`ANSWER` varchar(8) NOT NULL,
`USER` varchar(64) NOT NULL,
`QUESTION_ID` int NOT NULL,
`SCORE` bit NOT NULL,
`EXAM` int NOT NULL,
PRIMARY KEY (`ID`) 
);

CREATE TABLE `TYPE` (
`ID` int NOT NULL AUTO_INCREMENT,
`NAME` varchar(32) NOT NULL,
PRIMARY KEY (`ID`) 
);

CREATE TABLE `POWER` (
`ID` int NOT NULL AUTO_INCREMENT,
`POWER` varchar(256) NOT NULL,
PRIMARY KEY (`ID`) 
);

CREATE TABLE `COURSE` (
`ID` int NOT NULL,
`NAME` varchar(256) NOT NULL,
PRIMARY KEY (`ID`) 
);

CREATE TABLE `TYPE_POWER` (
`TYPE` int NOT NULL,
`POWER` int NOT NULL,
PRIMARY KEY (`TYPE`, `POWER`) 
);

CREATE TABLE `USER_TYPE` (
`USER` varchar(64) NOT NULL,
`TYPE` int NOT NULL,
PRIMARY KEY (`USER`, `TYPE`) 
);

CREATE TABLE `QUESTION_EXAM` (
`EXAM` int NOT NULL,
`QUESTION` int NOT NULL
);

CREATE TABLE `CHARPTER_COURSE` (
`CHARPTER` int NOT NULL,
`COURSE` int NOT NULL,
PRIMARY KEY (`CHARPTER`, `COURSE`) 
);

CREATE TABLE `QUESTION_CHARPTER` (
`QUESTION` int NOT NULL,
`CHARPTER` int NOT NULL,
PRIMARY KEY (`QUESTION`, `CHARPTER`) 
);


ALTER TABLE `QUESTION_EXAM` ADD CONSTRAINT `fk_QUESTION_EXAM_EXAM_1` FOREIGN KEY (`EXAM`) REFERENCES `EXAM` (`ID`);
ALTER TABLE `QUESTION_EXAM` ADD CONSTRAINT `fk_QUESTION_EXAM_QUESTION_1` FOREIGN KEY (`QUESTION`) REFERENCES `QUESTION` (`ID`);
ALTER TABLE `QUESTION_CHARPTER` ADD CONSTRAINT `fk_QUESTION_CHARPTER_QUESTION_1` FOREIGN KEY (`QUESTION`) REFERENCES `QUESTION` (`ID`);
ALTER TABLE `QUESTION_CHARPTER` ADD CONSTRAINT `fk_QUESTION_CHARPTER_CHARPTER_1` FOREIGN KEY (`CHARPTER`) REFERENCES `CHARPTER` (`ID`);
ALTER TABLE `CHARPTER_COURSE` ADD CONSTRAINT `fk_CHARPTER_COURSE_CHARPTER_1` FOREIGN KEY (`CHARPTER`) REFERENCES `CHARPTER` (`ID`);
ALTER TABLE `CHARPTER_COURSE` ADD CONSTRAINT `fk_CHARPTER_COURSE_COURSE_1` FOREIGN KEY (`COURSE`) REFERENCES `COURSE` (`ID`);
ALTER TABLE `ANSWER` ADD CONSTRAINT `fk_ANSWER_USER_1` FOREIGN KEY (`USER`) REFERENCES `USER` (`ID`);
ALTER TABLE `ANSWER` ADD CONSTRAINT `fk_ANSWER_EXAM_1` FOREIGN KEY (`EXAM`) REFERENCES `EXAM` (`ID`);
ALTER TABLE `USER_TYPE` ADD CONSTRAINT `fk_USER_TYPE_USER_1` FOREIGN KEY (`USER`) REFERENCES `USER` (`ID`);
ALTER TABLE `USER_TYPE` ADD CONSTRAINT `fk_USER_TYPE_TYPE_1` FOREIGN KEY (`TYPE`) REFERENCES `TYPE` (`ID`);
ALTER TABLE `TYPE_POWER` ADD CONSTRAINT `fk_TYPE_POWER_TYPE_1` FOREIGN KEY (`TYPE`) REFERENCES `TYPE` (`ID`);
ALTER TABLE `TYPE_POWER` ADD CONSTRAINT `fk_TYPE_POWER_POWER_1` FOREIGN KEY (`TYPE`) REFERENCES `POWER` (`ID`);

